% Reads in .csv data generated by the engineering team and reorders it so
% the column order matches the probe order in the standard Matlab analysis
% pipeline. DATA{1,2} contains 'raw' (background-subtracted) data,
% DATA{1,3} contains normalized data (normalized to the brightest
% non-control probe in the array), and DATA{1,4} contains
% baseline-subtracted data

function DATA = ReadCsvDataInput(fname)
    tab = readtable(fname);
    probes = tab.Properties.VariableNames;
    raw = find(contains(probes, 'Raw'));
    norm = find(contains(probes, 'Norm'));
     import_order = [1, 10:-1:2, 22:-1:15, 13, 12, 33:-1:23, 44:-1:34, 55:-1:45, ...
         66:-1:61, 59:-1:56, 87, 86, 82:-1:78, 99:-1:89, 110:-1:100, 120:-1:115, 113, 112];
    DATA = cell(1,4);
    DATA{1,2} = zeros(60,121);
    
    for i = 1:length(raw)
        DATA{1,2}(:,import_order(i)) = table2array(tab(:, raw(i)));
    end
    
    DATA{1,3} = zeros(60,121);
    for i = 1:length(norm)
        DATA{1,3}(:,import_order(i)) = table2array(tab(:, norm(i)));
    end
    
    DATA{1,4} = zeros(60,121);
    for i = 1:121
        DATA{1,4}(:,i) = DATA{1,2}(:,i) - mean(DATA{1,2}(3:7,i));
    end
end